2023-03-25 17:36:36,169 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Configure stats pid to 75035
2023-03-25 17:36:36,169 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from /Users/SML161/.config/wandb/settings
2023-03-25 17:36:36,169 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/settings
2023-03-25 17:36:36,169 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-25 17:36:36,169 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-25 17:36:36,169 INFO    MainThread:75035 [wandb_init.py:_log_setup():478] Logging user logs to /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/run-20230325_173636-vpv32e6f/logs/debug.log
2023-03-25 17:36:36,170 INFO    MainThread:75035 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/run-20230325_173636-vpv32e6f/logs/debug-internal.log
2023-03-25 17:36:36,170 INFO    MainThread:75035 [wandb_init.py:_jupyter_setup():428] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x174916fd0>
2023-03-25 17:36:36,170 INFO    MainThread:75035 [wandb_init.py:init():518] calling init triggers
2023-03-25 17:36:36,170 INFO    MainThread:75035 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'comment': 'Description: training binary resnet18 on A+V classes and excluding unknown class X'}
2023-03-25 17:36:36,170 INFO    MainThread:75035 [wandb_init.py:init():571] starting backend
2023-03-25 17:36:36,170 INFO    MainThread:75035 [wandb_init.py:init():575] setting up manager
2023-03-25 17:36:36,176 INFO    MainThread:75035 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-03-25 17:36:36,182 INFO    MainThread:75035 [wandb_init.py:init():582] backend started and connected
2023-03-25 17:36:36,186 INFO    MainThread:75035 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-03-25 17:36:36,186 INFO    MainThread:75035 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-25 17:36:36,186 INFO    MainThread:75035 [wandb_init.py:init():670] updated telemetry
2023-03-25 17:36:36,225 INFO    MainThread:75035 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-03-25 17:36:39,302 WARNING MsgRouterThr:75035 [router.py:message_loop():77] message_loop has been closed
2023-03-25 17:36:46,281 ERROR   MainThread:75035 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 713, in init
    result = run_init_handle.wait(
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Configure stats pid to 75035
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from /Users/SML161/.config/wandb/settings
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/settings
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_init.py:_log_setup():478] Logging user logs to /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/run-20230325_173721-evcw4qbk/logs/debug.log
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/run-20230325_173721-evcw4qbk/logs/debug-internal.log
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_init.py:init():518] calling init triggers
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'comment': 'Description: training resnet18 on A & E classes and excluding unknown class X'}
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_init.py:init():571] starting backend
2023-03-25 17:37:21,375 INFO    MainThread:75035 [wandb_init.py:init():575] setting up manager
2023-03-25 17:37:21,414 ERROR   MainThread:75035 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-03-25 17:37:41,812 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Configure stats pid to 75035
2023-03-25 17:37:41,812 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from /Users/SML161/.config/wandb/settings
2023-03-25 17:37:41,812 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/settings
2023-03-25 17:37:41,812 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-25 17:37:41,813 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-25 17:37:41,813 INFO    MainThread:75035 [wandb_init.py:_log_setup():478] Logging user logs to /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/run-20230325_173741-7y0l7mj4/logs/debug.log
2023-03-25 17:37:41,813 INFO    MainThread:75035 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/run-20230325_173741-7y0l7mj4/logs/debug-internal.log
2023-03-25 17:37:41,813 INFO    MainThread:75035 [wandb_init.py:init():518] calling init triggers
2023-03-25 17:37:41,813 INFO    MainThread:75035 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'comment': 'Description: training resnet18 on A & E classes and excluding unknown class X'}
2023-03-25 17:37:41,814 INFO    MainThread:75035 [wandb_init.py:init():571] starting backend
2023-03-25 17:37:41,814 INFO    MainThread:75035 [wandb_init.py:init():575] setting up manager
2023-03-25 17:37:41,824 ERROR   MainThread:75035 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-03-25 17:38:13,518 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Configure stats pid to 75035
2023-03-25 17:38:13,518 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from /Users/SML161/.config/wandb/settings
2023-03-25 17:38:13,519 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/settings
2023-03-25 17:38:13,519 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-25 17:38:13,519 INFO    MainThread:75035 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-25 17:38:13,519 INFO    MainThread:75035 [wandb_init.py:_log_setup():478] Logging user logs to /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/run-20230325_173813-kcxcmit4/logs/debug.log
2023-03-25 17:38:13,520 INFO    MainThread:75035 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/SML161/ecco12_ramu/rana-sierrae-cnn/wandb/run-20230325_173813-kcxcmit4/logs/debug-internal.log
2023-03-25 17:38:13,520 INFO    MainThread:75035 [wandb_init.py:init():518] calling init triggers
2023-03-25 17:38:13,520 INFO    MainThread:75035 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'comment': 'Description: training resnet18 on A & E classes and excluding unknown class X'}
2023-03-25 17:38:13,520 INFO    MainThread:75035 [wandb_init.py:init():571] starting backend
2023-03-25 17:38:13,520 INFO    MainThread:75035 [wandb_init.py:init():575] setting up manager
2023-03-25 17:38:13,528 ERROR   MainThread:75035 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/SML161/miniconda3/envs/opso080/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
